deployment:
  tasks:
    - export DEPLOYPATH=/home/kina3126/public_html/backup.kanpa.co.id
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH